name: Deploy Bot to Yandex Cloud

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Deploy Function
        id: sls-func
        uses: yc-actions/yc-sls-function@v2.0.0
        with:
           yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
           bucket: ''
           folder-id: 'b1g9ecpi49mbdba8d85m'
           function-name: 'telegram-hockey-trainer'
           runtime: 'python37'
           memory: '128Mb'
           entrypoint: 'bot.handler'
           environment: |
              TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }}
           include: |
              data
              templates
           exclude: |
              workflows
              infrastructure
              tests